### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by ethantkoenig**
Covering (most of) aws_tools, general_tools, gogs_tools. https://github.com/unfoldingWord-dev/door43.org/issues/220

### CODE REVIEW

**Review by phillip-hopper — COMMENTED** [review]
Not a requirement, but it is best for the file names of test files to start with 'test_' because that is the default for IntelliJ/PyCharm when the tests are run locally.

**Comment by phillip-hopper** [comment]
@ethantkoenig This could be merged if you rebase.

**Comment by ethantkoenig** [comment]
@phillip-hopper Renamed the test files and rebased.

**Review by phillip-hopper — APPROVED** [review]
LGTM  👍

**Pull request merged**
